dependencies:
  # Adding github repos for chainlink contracts
  # - <organization/repo>@<version> 
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    version: 0.8.9
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2'
dotenv: .env
networks:
  sepolia:
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306' # chainlink eth usd price feed contract
    verify: True # verify contract
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
